<a href="https://colab.research.google.com/github/emanuelmejia/course_time_series_python/blob/main/L00-Review/Review_Python/4-Manejando_Datos/4.1-Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# <div style="padding:10px;background-color: #FF4D4D; color:white;font-size:28px;"><strong>Numpy</strong></div>

Existen algunos paquetes especializados en aplicaciones específicas, algunos son tan populares que casi todos los programadores los usan.

Un paquete en particular, [**NumPy**](https://numpy.org/), se encuentra en el núcleo de la computación científica y de datos en Python (incluyendo el ecosistema [PyData](https://pydata.org/)). Muchos otros paquetes de ciencia de datos (como `scikit-learn`, `scipy`, `pandas`) están construidos sobre **NumPy**, por lo que es muy importante entender su función.

Contiene, entre otras cosas:

- Un poderoso objeto de **arreglo N-dimensional**
- Capacidades de álgebra lineal, transformada de Fourier.
- Funciones sofisticadas y generación de números aleatorios.
- Vectorización de funciones.
- Herramientas para integrar código en **C/C++** y **Fortran**

A menudo usamos **NumPy** para trabajar con datos.

## <a style="padding:3px;color: #FF4D4D; "><strong>Arreglos</strong></a>

Tradicionalmente, `numpy` se renombra como `np`. La razón por la que hacemos esto es que existe una convención en la comunidad **PyData** de importar los paquetes de datos con nombres más cortos.

In [214]:
import numpy as np
print(np.__version__)

2.0.2


In [215]:
np.arange(0,20)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

La función `arange` es análoga a la función `range` que estudiamos anteriormente.

In [216]:
miArreglo = np.arange(10)

Pero en lugar de devolver un objeto de tipo `range`, el tipo de objeto que devuelve es un `numpy.ndarray`, algo que llamaremos un `arreglo`.

In [217]:
type(miArreglo)

numpy.ndarray

Los Arreglos son similares a las otras secuencias que vimos anteriormente. Por ejemplo, podemos acceder a sus elementos a través del índice.

In [218]:
miArreglo[2] = 12
miArreglo

array([ 0,  1, 12,  3,  4,  5,  6,  7,  8,  9])

Sin embargo, los arreglos también tienen características únicas.

Para empezar, todos los objetos contenidos en el arreglo **deben ser del mismo tipo**.

Aunque esto podría parecer una restricción molesta comparando los arreglos con otros objetos, permite que este nuevo tipo de secuencia trabaje de manera MUY eficiente en grandes volúmenes de datos.

In [219]:
# miArreglo[5] = "pluma"

Puede accederse al tipo de datos que contiene un arreglo utilizando la propiedad `dtype`. Eso quiere decir que, una vez creado, no puede cambiarse directamente el tipo de un arreglo.

In [220]:
miArreglo.dtype

dtype('int64')

Los tipos más comunes en NumPy son:

##### Tipo Entero y Booleanos:
- `bool_` : Booleano (Verdadero o Falso) almacenado como un byte
- `int_` : Tipo entero predeterminado (igual que long en C; normalmente int64 o int32)
- `intc` : Idéntico al tipo int en C (normalmente int32 o int64)
- `intp` : Entero usado para indexación (igual que ssize_t en C; normalmente int32 o int64)
- `int8` : Entero de 8 bits con signo (-128 a 127)
- `int16` : Entero de 16 bits con signo (-32,768 a 32,767)
- `int32` : Entero de 32 bits con signo (-2,147,483,648 a 2,147,483,647)
- `int64` : Entero de 64 bits con signo (-9,223,372,036,854,775,808 a 9,223,372,036,854,775,807)
- `uint8` : Entero sin signo de 8 bits (0 a 255)
- `uint16` : Entero sin signo de 16 bits (0 a 65,535)
- `uint32` : Entero sin signo de 32 bits (0 a 4,294,967,295)
- `uint64` : Entero sin signo de 64 bits (0 a 18,446,744,073,709,551,615)

##### Tipos de punto flotante
- `float_` : Abreviatura de float64
- `float16` : Punto flotante de media precisión: 1 bit de signo, 5 bits de exponente, 10 bits de mantisa
- `float32` : Punto flotante de precisión simple: 1 bit de signo, 8 bits de exponente, 23 bits de mantisa
- `float64` : Punto flotante de doble precisión: 1 bit de signo, 11 bits de exponente, 52 bits de mantisa

##### Tipos complejos
- `complex_` : Abreviatura de complex128
- `complex64` : Número complejo representado por dos float32 (parte real e imaginaria)
- `complex128` : Número complejo representado por dos float64 (parte real e imaginaria)

Además, una vez que el arreglo fue creado su tamaño es fijo, lo que les permite optimizarse para un alto desempeño.

Por lo tanto, funciones como `pop` o `append` no funcionarán en el arreglo.

In [221]:
# miArreglo.append(20)

In [222]:
# miArreglo.pop()

## <a style="padding:3px;color: #FF4D4D; "><strong>Construcción de Arreglos</strong></a>

Al igual que con un rango, podemos utilizar pasos en nuestra creación de arreglos por medio de la función `arange`

In [223]:
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

También podemos llenar el espacio entre dos números, por ejemplo imaginemos que deseamos el rango entre 0 y 1 dividido en cinco números exactamente.

In [224]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

Y podemos también convertir esto en un tipo diferente si lo necesitamos, aunque debemos ser cuidadosos con la posibilidad de perder información

In [225]:
np.linspace(0,1,5).astype('int')

array([0, 0, 0, 0, 1])

También existen varias maneras de generar arreglos al vuelo al pasar objetos en la función `array`

In [226]:
np.array(range(20))

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [227]:
np.array(range(20)).dtype

dtype('int64')

Como mencionamos, los arreglos de **NumPy** deben contener el mismo tipo, no podemos mezclar por ejemplo flotantes y enteros.

In [228]:
np.array([1.0,0,2,3])

array([1., 0., 2., 3.])

In [229]:
np.array([1.0,0,2,3]).dtype

dtype('float64')

Esto permite asignaciones consistentes en la memoria que optimizan los procesos en los arreglos.

Sin embargo, hay ocasiones en que obtendremos un arreglo de un tipo que no necesariamente es el deseado.

In [230]:
np.array([True,2,2.0])

array([1., 2., 2.])

In [231]:
np.array([True,2,2.0]).dtype

dtype('float64')

Afortunadamente, durante la creación de nuestro arreglo, podemos definir el tipo deseado.

In [232]:
## Booleanos
np.array([True, 1, 2.0], dtype='bool')

array([ True,  True,  True])

In [233]:
## Flotantes
np.array([True, 1, 2.0], dtype='float')

array([1., 1., 2.])

In [234]:
## Enteros
np.array([True, 1, 2.0], dtype='int')

array([1, 1, 2])

In [235]:
## Enteros byte-8bits (del 0 al 255)
np.array([True, 1, 2.0], dtype='uint8')

array([1, 1, 2], dtype=uint8)

## <a style="padding:3px;color: #FF4D4D; "><strong>Vectorización</strong></a>

Los arreglos de **Numpy** nos permiten implementar muchos métodos como si fuesen listas de Python.

In [236]:
miArreglo

array([ 0,  1, 12,  3,  4,  5,  6,  7,  8,  9])

In [237]:
[x * x for x in miArreglo]

[np.int64(0),
 np.int64(1),
 np.int64(144),
 np.int64(9),
 np.int64(16),
 np.int64(25),
 np.int64(36),
 np.int64(49),
 np.int64(64),
 np.int64(81)]

Sin embargo, esto no siempre es la manera recomendada de utilizar los arreglos. Normalmente, buscaremos **vectorizar** al computar una función

In [238]:
miArreglo * miArreglo

array([  0,   1, 144,   9,  16,  25,  36,  49,  64,  81])

Midiendo los tiempos de cada uno de los métodos podemos ver que el segundo fue mucho más eficiente.

In [239]:
%timeit [x * x for x in miArreglo]

2.26 µs ± 101 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [240]:
%timeit miArreglo * miArreglo

603 ns ± 10.2 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


ms = milisegundos o $10^{-3} $ segundos

$\mu s$ = microsegundos o $10^{-6} $ segundos

ns = nanosegundos o $ 10 ^{-9} $ segundos

La vectorización, en términos simples, te permite aplicar una función a todo un arreglo en lugar de hacerlo valor por valor, similar a lo que hicimos con `map` en lecciones anteriores.

Esto normalmente hace que las cosas sean mucho más concisas, legibles y rápidas.

Esto permite que muchas operaciones que requieren bucles, podemos evitarlas con una operación vectorial con arreglos de NumPy. Esto debido a que los bucles además de que pueden introducir errores, suelen ser menos eficientes.

Evaluemos la sintaxis de algunas operaciones que pueden realizarse a un arreglo por medio de vectorización.

In [241]:
arrInt = np.random.randint(0,50,20)
arrInt

array([29, 10, 28, 15, 49, 16, 22,  9, 48, 48, 28, 25, 39, 46,  1, 16, 36,
       39,  2, 43])

In [242]:
# Sumar 10 a cada número
arrInt + 10

array([39, 20, 38, 25, 59, 26, 32, 19, 58, 58, 38, 35, 49, 56, 11, 26, 46,
       49, 12, 53])

In [243]:
# Duplicar cada elemento
arrInt * 2

array([58, 20, 56, 30, 98, 32, 44, 18, 96, 96, 56, 50, 78, 92,  2, 32, 72,
       78,  4, 86])

In [244]:
# Elevar cada elemento al cubo
arrInt ** 3

array([ 24389,   1000,  21952,   3375, 117649,   4096,  10648,    729,
       110592, 110592,  21952,  15625,  59319,  97336,      1,   4096,
        46656,  59319,      8,  79507])

Podemos llevar esto un paso más allá y definir nuestras propias funciones vectorizadas, las cuales funcionarán con una eficiencia extremadamente alta. Supongamos que necesitamos realizar una serie de transformaciones. Podemos incluirlas en una función para que sean un poco más legibles.

Simplemente podemos declarar exactamente lo que queremos que se haga con cada objeto.

In [245]:
def opera(obj):
    return ((obj * 2) - 1)

Esta función podríamos aplicarla a un entero.

In [246]:
opera(2)

3

Y podríamos también aplicarlo a un arreglo

In [247]:
opera(arrInt)

array([57, 19, 55, 29, 97, 31, 43, 17, 95, 95, 55, 49, 77, 91,  1, 31, 71,
       77,  3, 85])

Aunque esto funcionó, a veces no lo hará, como por ejemplo si incluimos filtros o tenemos transformaciones específicas para ciertos valores. En esos casos, necesitamos usar la función `vectorize` para poder pasarle un arreglo. Definamos por ejemplo la siguiente función:

In [248]:
def paridad(x):
    if x % 2 == 0:
        return "par"
    else:
        return "impar"

Si intentamos aplicarla directamente sobre un arreglo obtendremos un error porque `paridad` no está diseñada para manejar arreglos, solo escalares:

In [249]:
paridad(3)

'impar'

In [250]:
# paridad(arrInt)

Pero `np.vectorize` permite que una función que trabaja sobre escalares se aplique elemento por elemento sobre un arreglo, como si fuera una versión “universal” de la función.

In [251]:
paridadVec = np.vectorize(paridad)

In [252]:
paridadVec(3)

array('impar', dtype='<U5')

In [253]:
paridadVec(arrInt)

array(['impar', 'par', 'par', 'impar', 'impar', 'par', 'par', 'impar',
       'par', 'par', 'par', 'impar', 'impar', 'par', 'impar', 'par',
       'par', 'impar', 'par', 'impar'], dtype='<U5')

## <a style="padding:3px;color: #FF4D4D; "><strong>Selección Booleana</strong></a>

La selección Booleana en los arreglos es útil porque nos permite pedirle a la computadora lo que queremos en lugar de decirle exactamente cómo hacerlo (pensamiento declarativo en lugar de imperativo).

Por lo que la computadora lo ejecutará de la forma más eficiente posible.

In [254]:
arr = np.arange(20)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [255]:
# Forma imperativa
[x for x in arr if x % 2 == 0]

[np.int64(0),
 np.int64(2),
 np.int64(4),
 np.int64(6),
 np.int64(8),
 np.int64(10),
 np.int64(12),
 np.int64(14),
 np.int64(16),
 np.int64(18)]

In [256]:
# Forma declarativa Python NumPy
arr[arr % 2 == 0]

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

Esto, además de que es más corto de escribir y más eficiente, introduce una nueva sintaxis así que desglosemos su significado. Observemos lo que tenemos dentro de los corchetes cuadrados

In [257]:
arr % 2 == 0

array([ True, False,  True, False,  True, False,  True, False,  True,
       False,  True, False,  True, False,  True, False,  True, False,
        True, False])

Tenemos una lista de objetos booleanos que corresponde a aplicar la función a cada elemento del arreglo original y evaluar la condición propuesta.

Esto esencialmente es una operación de filtrado mucho más concisa conocida como **Selección Booleana**.

Al ingresar esta lista de booleanos como "índice" de nuestro arreglo, estamos pidiéndole que filtre en el arreglo original, los valores en que la selección booleana arrojaron un resultado `True`, es tan simple como eso.

¿Y qué tan importante es esta optimización?

In [258]:
arr2 = np.arange(20000)

In [259]:
%timeit [x for x in arr2 if x % 2 == 0]

5.19 ms ± 1.79 ms per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [260]:
%timeit arr2[arr2 % 2 == 0]

380 µs ± 7.15 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


Podemos ver que que es considerablemente más rápida la selección booleana pues está anclada en una librería de álgebra lineal optimizada que se encuentra en la computadora.

Adicionalmente, permite operaciones unidas de maneras mucho más fáciles de entender que intentándolo por otros medios menos legibles como un bucle o una comprensión.

In [261]:
# Mayores a 15 o menores a 5
arr[(arr > 15) | (arr < 5)]

array([ 0,  1,  2,  3,  4, 16, 17, 18, 19])

In [262]:
# Mayores a 5 y menores a 15
arr[(arr > 5) & (arr < 15)]

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14])

En estos casos debemos usar paréntesis alrededor de las condiciones; de lo contrario, no funcionará, ya que Python no sabrá cómo combinar las distintas expresiones lógicas.

In [263]:
arr.size

20

Además la selección Booleana no necesariamente tiene que hacerse con el mismo arreglo.

Por ejemplo, imaginemos que el arreglo `arr` corresponde al número de cliente de un banco (del 1 al 20) y creamos otro arreglo que simula los saldos en sus cuentas.

In [264]:
saldos = np.random.randint(0,50000,20)
saldos

array([ 8736, 40394, 39185, 40452, 18370,  7781, 10208,  2896, 25863,
       40631, 38718, 26221, 15777, 43630,  9869,  8749,   387, 15504,
       10741, 36051])

Podemos seleccionar los elementos del arreglo de números original con base en el de los saldos. Imaginemos que queremos saber qué clientes tienen un saldo mayor a $25,000

In [265]:
arr[saldos > 25000]

array([ 1,  2,  3,  8,  9, 10, 11, 13, 19])

Únicamente debemos asegurar que estamos filtrando con un arreglo del mismo tamaño que el que estás tratando de filtrar; de lo contrario, NumPy no sabrá exactamente cómo aplicar el filtro.

## <a style="padding:3px;color: #FF4D4D; "><strong>Arreglos Multidimensionales</strong></a>

El tipo `numpy.ndarray` se refiere a un **arreglo de n-dimensiones** y `n` puede tomar el valor que nosotros quedamos.

Por ejemplo, podemos crear una matriz de dos dimensiones, que contenga números aleatorios distribuidos uniformemente entre 0 y 1.

In [266]:
np.random.rand(4,4)

array([[0.05294962, 0.68533718, 0.9750775 , 0.98338404],
       [0.79870956, 0.93592701, 0.68191272, 0.14595921],
       [0.84034054, 0.78628155, 0.82339545, 0.22624349],
       [0.56932052, 0.57465401, 0.05435295, 0.23690817]])

O podemos crear un cubo tridimensional de números aleatorios.

In [267]:
np.random.rand(4,4,4)

array([[[0.53409213, 0.78751232, 0.4523459 , 0.4479461 ],
        [0.16697114, 0.86338214, 0.16367861, 0.84810662],
        [0.08640889, 0.49082568, 0.81102034, 0.93925734],
        [0.47828488, 0.72375263, 0.4777146 , 0.44310355]],

       [[0.55103153, 0.88250252, 0.46366854, 0.08532435],
        [0.41823285, 0.13436493, 0.87309414, 0.55268756],
        [0.35444542, 0.69444345, 0.25275158, 0.98401623],
        [0.60246496, 0.46532308, 0.13952068, 0.53463356]],

       [[0.70850428, 0.21428305, 0.43857543, 0.73534334],
        [0.39692818, 0.40171801, 0.48893274, 0.05087871],
        [0.27678731, 0.82536834, 0.4938049 , 0.74164262],
        [0.92805131, 0.83397597, 0.04520281, 0.0484344 ]],

       [[0.08224745, 0.47879538, 0.19726054, 0.11676716],
        [0.99470773, 0.5398752 , 0.78153472, 0.19344551],
        [0.0454729 , 0.09880739, 0.71501886, 0.55002049],
        [0.65175339, 0.6086106 , 0.12890221, 0.27339493]]])

Y podríamos continuar en espacios dimensionales más altos como puede verse en la documentación de la función.

In [268]:
?np.random.rand

Los números que creamos se tomaron de una distribución uniforme, sin embargo **Numpy** ofrece muchas otras distribuciones con las que podemos trabajar.

In [269]:
?np.random

Viendo la documentación del módulo `np.random`, tenemos una gran variedad de funciones a nuestra disposición, por ejemplo podemos generar un arreglo de número generados bajo una normal estándar.

In [270]:
np.random.randn(12)

array([-1.52237469, -0.91622528,  0.71040422,  0.51059321, -0.99847341,
        1.64936636, -1.51283942, -0.25458005,  0.35852896, -0.06782042,
        0.82295336,  0.68131742])

Y este mismo arreglo podríamos reacomodarlo en una matriz 4x3 utilizando el método `reshape`.

In [271]:
ar = np.random.randn(12).reshape(4,3)
ar

array([[-0.30436553, -1.44255122, -0.18171044],
       [-1.16355565,  1.94822814, -1.04836661],
       [ 0.73494715,  0.5067993 ,  1.199247  ],
       [ 0.53683485, -0.91281551,  2.23822917]])

Podemos también crear una matriz nula con el comando `zeros` que utiliza las dimensiones de la matriz como argumento

In [272]:
np.zeros((5,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

Una gran ventaja con NumPy es que muchas veces un resultado puede ser utilizado como entrada de otra función. Por ejemplo la función devuelve una tupla como la que se necesita en la función `zeros`

In [273]:
ar.shape

(4, 3)

In [274]:
np.zeros(ar.shape)

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [275]:
# np.random.seed(10)

In [276]:
arr1 = np.random.randint(1,10,25).reshape(5,5).astype('uint')
arr1

array([[1, 4, 1, 9, 3],
       [1, 1, 5, 8, 4],
       [1, 8, 1, 2, 6],
       [9, 7, 8, 2, 8],
       [2, 6, 3, 6, 9]], dtype=uint64)

In [277]:
arr2 = np.random.randint(1,10,25).reshape(5,5).astype('uint')
arr2

array([[2, 9, 9, 6, 5],
       [9, 6, 7, 4, 1],
       [6, 2, 5, 9, 8],
       [1, 9, 4, 7, 1],
       [1, 4, 6, 2, 7]], dtype=uint64)

Nuevamente podemos operar de forma vectorial si deseamos por ejemplo duplicar los elementos del primer arreglo.

In [278]:
arr1 * 2

array([[ 2,  8,  2, 18,  6],
       [ 2,  2, 10, 16,  8],
       [ 2, 16,  2,  4, 12],
       [18, 14, 16,  4, 16],
       [ 4, 12,  6, 12, 18]], dtype=uint64)

Podemos multiplicar elementos rápidamente uno a uno

In [279]:
arr1 * arr2

array([[ 2, 36,  9, 54, 15],
       [ 9,  6, 35, 32,  4],
       [ 6, 16,  5, 18, 48],
       [ 9, 63, 32, 14,  8],
       [ 2, 24, 18, 12, 63]], dtype=uint64)

Digamos ahora que queremos comparar valores entre ambos arreglos

In [280]:
arr1 < arr2

array([[ True,  True,  True, False,  True],
       [ True,  True,  True, False, False],
       [ True, False,  True,  True,  True],
       [False,  True, False,  True, False],
       [False, False,  True, False, False]])

Esto se vuelve sorprendentemente fácil sin necesidad de hacer bucles complejos para lograr este mismo resultado.

Observemos que la salida fue un arreglo también

## <a style="padding:3px;color: #FF4D4D; "><strong>Funciones Básicas</strong></a>

Otra ventaja de los arreglos de Numpy es que tienen integradas muchas funciones comunes. Por ejemplo:

In [281]:
ar

array([[-0.30436553, -1.44255122, -0.18171044],
       [-1.16355565,  1.94822814, -1.04836661],
       [ 0.73494715,  0.5067993 ,  1.199247  ],
       [ 0.53683485, -0.91281551,  2.23822917]])

In [282]:
# Tamaño del arreglo
ar.size

12

In [283]:
# Forma del arreglo
ar.shape

(4, 3)

In [284]:
# Suma de valores
ar.sum()

np.float64(2.110920639618499)

In [285]:
# Valor máximo
ar.max()

np.float64(2.2382291678256543)

In [286]:
# Valor mínimo
ar.min()

np.float64(-1.4425512248669783)

In [287]:
# Ubicación del mínimo
ar.argmin()

np.int64(1)

In [288]:
# Ubicación del máximo
ar.argmax()

np.int64(11)

In [289]:
# Media
ar.mean()

np.float64(0.1759100533015416)

In [290]:
# Varianza
ar.var()

np.float64(1.3708404961047431)

In [291]:
# Desviación estándar
ar.std()

np.float64(1.1708289781623715)

In [292]:
# Mediana
np.median(ar)

np.float64(0.16254443209745756)

Recordemos ahora los arreglos que estábamos comparando

Habrá veces en que queremos hacer estas operaciones por fila o por columna

In [293]:
arr1

array([[1, 4, 1, 9, 3],
       [1, 1, 5, 8, 4],
       [1, 8, 1, 2, 6],
       [9, 7, 8, 2, 8],
       [2, 6, 3, 6, 9]], dtype=uint64)

Por ejemplo aquí tenemos la suma por columnas `axis = 0`

In [294]:
arr1.sum(axis = 0)

array([14, 26, 18, 27, 30], dtype=uint64)

O la media por filas `axis = 1`

In [295]:
arr1.mean(axis = 1)

array([3.6, 3.8, 3.6, 6.8, 5.2])

El máximo de cada fila `axis = 1`

In [296]:
arr1.max(axis = 1)

array([9, 8, 8, 9, 9], dtype=uint64)

El mínimo de cada columna `axis = 0`

In [297]:
arr1.min(axis = 0)

array([1, 1, 1, 2, 3], dtype=uint64)

Tenemos también la posibilidad de calcular la transpuesta con las funciones `.T` o `.transpose()`

In [298]:
arr1.T

array([[1, 1, 1, 9, 2],
       [4, 1, 8, 7, 6],
       [1, 5, 1, 8, 3],
       [9, 8, 2, 2, 6],
       [3, 4, 6, 8, 9]], dtype=uint64)

In [299]:
arr1.transpose()

array([[1, 1, 1, 9, 2],
       [4, 1, 8, 7, 6],
       [1, 5, 1, 8, 3],
       [9, 8, 2, 2, 6],
       [3, 4, 6, 8, 9]], dtype=uint64)

También podemos aplanar el arreglo con la función `flatten()` que devuelve un nuevo arreglo, mientras que ravel apunta al arreglo original.

In [300]:
flat = arr1.flatten()
flat

array([1, 4, 1, 9, 3, 1, 1, 5, 8, 4, 1, 8, 1, 2, 6, 9, 7, 8, 2, 8, 2, 6,
       3, 6, 9], dtype=uint64)

In [301]:
flatF = arr1.flatten(order = 'F')
flatF

array([1, 1, 1, 9, 2, 4, 1, 8, 7, 6, 1, 5, 1, 8, 3, 9, 8, 2, 2, 6, 3, 4,
       6, 8, 9], dtype=uint64)

In [302]:
flat[0] = 11
flat

array([11,  4,  1,  9,  3,  1,  1,  5,  8,  4,  1,  8,  1,  2,  6,  9,  7,
        8,  2,  8,  2,  6,  3,  6,  9], dtype=uint64)

In [303]:
arr1

array([[1, 4, 1, 9, 3],
       [1, 1, 5, 8, 4],
       [1, 8, 1, 2, 6],
       [9, 7, 8, 2, 8],
       [2, 6, 3, 6, 9]], dtype=uint64)

O podemos también utilizar la función `ravel()`, sin embargo esta segunda apunta al arreglo original

In [304]:
rav = arr1.ravel()
rav

array([1, 4, 1, 9, 3, 1, 1, 5, 8, 4, 1, 8, 1, 2, 6, 9, 7, 8, 2, 8, 2, 6,
       3, 6, 9], dtype=uint64)

In [305]:
rav[0] = 11
rav

array([11,  4,  1,  9,  3,  1,  1,  5,  8,  4,  1,  8,  1,  2,  6,  9,  7,
        8,  2,  8,  2,  6,  3,  6,  9], dtype=uint64)

In [306]:
arr1

array([[11,  4,  1,  9,  3],
       [ 1,  1,  5,  8,  4],
       [ 1,  8,  1,  2,  6],
       [ 9,  7,  8,  2,  8],
       [ 2,  6,  3,  6,  9]], dtype=uint64)

Podemos usar otras funciones útiles como `cumsum` y `cumprod` para obtener las sumas y productos acumulativos. Esto funciona para arreglos de cualquier dimensión.

In [307]:
arr1.cumsum()

array([ 11,  15,  16,  25,  28,  29,  30,  35,  43,  47,  48,  56,  57,
        59,  65,  74,  81,  89,  91,  99, 101, 107, 110, 116, 125],
      dtype=uint64)

In [308]:
arr1.cumprod()

array([             11,              44,              44,             396,
                  1188,            1188,            1188,            5940,
                 47520,          190080,          190080,         1520640,
               1520640,         3041280,        18247680,       164229120,
            1149603840,      9196830720,     18393661440,    147149291520,
          294298583040,   1765791498240,   5297374494720,  31784246968320,
       286058222714880], dtype=uint64)

Recordemos también que al comparar dos arreglos obtuvimos a su vez un arreglo (de Booleanos). Podemos también operar sobre este:

In [309]:
arr1 > arr2

array([[ True, False, False,  True, False],
       [False, False, False,  True,  True],
       [False,  True, False, False, False],
       [ True, False,  True, False,  True],
       [ True,  True, False,  True,  True]])

Y calcular cuántas veces fueron mayores los valores del primer arreglo.

In [310]:
(arr1 > arr2).sum()

np.int64(12)

O cuántas veces contenían el mismo valor

In [311]:
(arr1 == arr2).sum()

np.int64(0)

## <a style="padding:3px;color: #FF4D4D; "><strong>NaN</strong></a>

Hay un tipo de objeto que aún no se ha mencionado y que es un poco difícil de describir: este es el valor `NaN` o "not a number" (no es un número).

Esto seguramente aparecerá y puede alterar nuestro análisis. Los NaN son técnicamente flotantes, pero surgen en ciertas operaciones. Una forma en la que esto puede ocurrir es debido a divisiones extrañas que no devuelven un número real.

In [312]:
problema = np.array([0.])/np.array([0.])

/tmp/ipykernel_6682/3713928926.py:1: RuntimeWarning: invalid value encountered in divide
  problema = np.array([0.])/np.array([0.])


In [313]:
problema

array([nan])

También podemos obtener este valor de lo siguiente.

In [314]:
np.nan

nan

Puede que nos estemos preguntando por qué esto es importante.

Podríamos encontrarnos con estos valores en nuestro trabajo y tener que manejarlos. Si están dentro de un arreglo, necesitaremos asegurarnos de que se manejen correctamente, ya que pueden alterar nuestros cálculos.

In [315]:
ar = np.linspace(0,10,11).astype(np.float32)
ar

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
      dtype=float32)

In [316]:
ar[0] = np.nan
ar

array([nan,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
      dtype=float32)

In [317]:
ar.min()

np.float32(nan)

In [318]:
ar.max()

np.float32(nan)

In [319]:
ar.mean()

np.float32(nan)

Debemos estar al tanto de que existe una representación de valores faltantes o ilegales. En NumPy, estos valores no se manejan a menos que se sea explícito.